# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. What explains the datatype of the array?

In [2]:
# YOUR CODE HERE

my_array = np.array([[0,1,2,3],[1,3,5,7]])

print(my_array.shape)
print(my_array.dtype)

my_array2 = np.array([0, "string stuff", 16, 17])

print(my_array2.shape)
print(my_array2.dtype)

print(my_array2[0])
print(my_array2[0].dtype)


(2, 4)
int64
(4,)
<U21
0
<U1


The data type of the array is ruled here by the string. The integers are treated as strings, because it is supposed to be all one data type going into this array.

---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [3]:
# YOUR CODE HERE

my_array3 = np.array([[0,1,2,3,4],[0,1,4,5,9]])

print(my_array3.size)
print(my_array3.shape)
print(my_array3.dtype)

10
(2, 5)
int64


Size represents the number of observations in the array, so rows x columns.

---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [4]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE
table1 = np.random.random(size = (num_samples,num_features))

print(table1.shape)

(100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [5]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE
image_layout = np.random.random(size = (num_images, num_rows, num_cols, num_channels))


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over all the elements in the array. Print the output.

In [6]:
# YOUR CODE HERE
my_array4 = np.array([[7,3],[3,9],[1,2]])
print(f'1. {my_array4.shape}')
print(f'2. {my_array4.sum()}')
print(f'3. {my_array4.sum(axis = 0)}')
print(f'4. {my_array4.sum(axis = 1,dtype=float)}')
print(f'5. {my_array4[0,:]}')
print(f'6. {my_array4[1,:]}')
print(f'7. {my_array4[1,0]}')
my_array4[2,1] = 10
print(f'8. {my_array4}')
print(f'9. ')
for i in my_array4.flatten():
    print(i)



1. (3, 2)
2. 25
3. [11 14]
4. [10. 12.  3.]
5. [7 3]
6. [3 9]
7. 3
8. [[ 7  3]
 [ 3  9]
 [ 1 10]]
9. 
7
3
3
9
1
10


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [7]:
# YOUR CODE HERE
array1 = np.random.rand(3,2)
print(f'1. {array1}')

array2 = np.arange(start = 1991, stop = 2018)
print(f'2. {array2}')

array3 = np.zeros(shape = [3,5,10])
print(f'3. {array3}')

array4 = np.ones(shape = [3,5,10])
print(f'4. {array4}')

array5 = np.ones(shape = [2,3])*5
print(f'5. {array5}')

array6 = np.random.standard_normal(size = [10])
print(f'6. {array6}')

1. [[0.28999571 0.50818013]
 [0.47655793 0.57281228]
 [0.53403895 0.66869277]]
2. [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
3. [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
4. [[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [8]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d (Hint: use np.reshape());
2. Convert the years_3d array to a flat 1D array. Call this array years_1d (Hint: use np.flatten());
3. Add a new dimension (axis=0) to the years_1d array. Call this array years_2d (Hint: use np.expand_dims());
4. Remove the first axis from years_2d array. Call this array years_1d (Hint: use np.squeeze()).

For each exercise print the array and its shape.

In [9]:
# YOUR CODE HERE
years_3d = years.reshape([3,3,3])
print(years_3d)

years_1d = years_3d.flatten()

years_2d = np.expand_dims(years_1d, axis = 0)

years_2d.shape

years_1d = np.squeeze(years_2d, axis = 0)

[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [10]:
# YOUR CODE HERE
# stacked 1
years_stacked = np.stack([years_1d, years_1d])
print(years_stacked.shape)
years_stacked2 = np.stack([years_2d, years_2d], axis = 0)
print(years_stacked2.shape)
years_stacked3 = np.stack([years_2d, years_2d], axis = 1)
print(years_stacked3.shape)
years_stacked4 = np.stack([years_3d, years_3d], axis = 2)
print(years_stacked4.shape)

years_concat = np.concatenate([years_1d,years_1d],axis = 0)
print(years_concat.shape)
years_concat2 = np.concatenate([years_2d,years_2d],axis = 0)
print(years_concat2.shape)
years_concat3 = np.concatenate([years_2d,years_2d],axis = 1)
print(years_concat3.shape)
years_concat4 = np.concatenate([years_3d, years_3d], axis = 2)
print(years_concat4.shape)

(2, 27)
(2, 1, 27)
(1, 2, 27)
(3, 3, 2, 3)
(54,)
(2, 27)
(1, 54)
(3, 3, 6)


---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [11]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [12]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [13]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [14]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [15]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[5.31221554e-01, 2.37281923e-01, 8.72005547e-01, 9.89537574e-01],
       [9.44649530e-01, 2.59047822e-02, 2.41036029e-01, 2.09232762e-01],
       [6.91936843e-01, 7.02465192e-01, 5.92360703e-01, 2.85496978e-01],
       [9.10061264e-02, 4.74607622e-01, 2.44213847e-01, 3.08055169e-02],
       [6.55060658e-01, 9.80750478e-04, 4.46020788e-01, 9.63664756e-01],
       [3.86439740e-01, 4.09421652e-01, 2.32061314e-02, 3.67139198e-02],
       [3.02058733e-01, 9.58056443e-01, 7.91801052e-01, 5.15142500e-01],
       [9.26690622e-02, 6.01623233e-01, 4.45338123e-01, 8.85537478e-01],
       [7.66971472e-01, 4.99193674e-01, 5.89632232e-02, 5.72399954e-01],
       [2.03701092e-01, 4.48716641e-01, 3.28975282e-01, 4.14938107e-01]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [16]:
# YOUR CODE HERE
means = my_array.mean(axis = 0,keepdims = True)
stds = my_array.std(axis = 0, keepdims = True)

standardized = (my_array - means)/stds

print(standardized)

[[ 0.22961753 -0.71353925  1.73054494  1.45296581]
 [ 1.69798882 -1.47320181 -0.60454839 -0.81822313]
 [ 0.80042969  0.95827025  0.69563471 -0.5962452 ]
 [-1.33389469  0.13937912 -0.59278792 -1.33756119]
 [ 0.66945662 -1.56277561  0.15405964  1.37765927]
 [-0.28460374 -0.09489096 -1.41069374 -1.32036393]
 [-0.58429959  1.8768327   1.43372397  0.07217099]
 [-1.32798845  0.59585707  0.15153323  1.15025863]
 [ 1.06693003  0.22773827 -1.27836382  0.23882701]
 [-0.93363622  0.04633023 -0.27910262 -0.21948825]]


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [17]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [18]:
# YOUR CODE HERE
# 1. 
crop_1 = my_image[1:-1,1:-1]
print(crop_1)

crop_2 = my_image[2:-2, 2:-2]
print(crop_2)

reverse = my_image[::-1,:]
print(reverse)



[[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]
[[0.48]]
[[0.8  0.84 0.88 0.92 0.96]
 [0.6  0.64 0.68 0.72 0.76]
 [0.4  0.44 0.48 0.52 0.56]
 [0.2  0.24 0.28 0.32 0.36]
 [0.   0.04 0.08 0.12 0.16]]
